/* Generated By:JJTree: Do not edit this line. ASTCalcUnit.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCalcUnit extends SimpleNode {
  public ASTCalcUnit(int id) {
    super(id);
  }

  public ASTCalcUnit(Calc p, int id) {
    super(p, id);
  }
  /* inserted */
  public int calculate() {
    if (jjtGetNumChildren() >= 1)
      System.out.println(
        "result= " + jjtGetChild(0).calculate());
    return 0;
  }
}
/* JavaCC - OriginalChecksum=7e0b5e49f3f79df78792c4adbbc7942f (do not edit this line) */
