/* Generated By:JJTree: Do not edit this line. ASTLiteral.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLiteral extends SimpleNode {
  public ASTLiteral(int id) {
    super(id);
  }

  public ASTLiteral(Calc p, int id) {
    super(p, id);
  }
/* inserted */
  int litValue;
  public int calculate() {
    return litValue;
  }
}
/* JavaCC - OriginalChecksum=d0c1324b8a725b3c6c9b69d348d074e4 (do not edit this line) */
