/* Generated By:JJTree: Do not edit this line. ASTMulNode.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMulNode extends SimpleNode {
  public ASTMulNode(int id) {
    super(id);
  }

  public ASTMulNode(Calc p, int id) {
    super(p, id);
  }
/* inserted */
  public int calculate() {
    return jjtGetChild(0).calculate() * jjtGetChild(1).calculate();
  }
}
/* JavaCC - OriginalChecksum=b963717e7466c3cf1f1725e3a27aed59 (do not edit this line) */
