/* Generated By:JJTree: Do not edit this line. ASTAddNode.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAddNode extends SimpleNode {
  public ASTAddNode(int id) {
    super(id);
  }

  public ASTAddNode(Calc p, int id) {
    super(p, id);
  }
  /* inserted */
  public int calculate() {
    return jjtGetChild(0).calculate()+jjtGetChild(1).calculate();
  }
}
/* JavaCC - OriginalChecksum=a70545ec3f647926ebc31604d7764523 (do not edit this line) */
