/* Generated By:JJTree: Do not edit this line. ASTDivNode.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDivNode extends SimpleNode {
  public ASTDivNode(int id) {
    super(id);
  }

  public ASTDivNode(Calc p, int id) {
    super(p, id);
  }
/* inserted */
  public int calculate() {
    return jjtGetChild(0).calculate()/jjtGetChild(1).calculate();
  }
}
/* JavaCC - OriginalChecksum=75095d0e7bf61e9c676b90289ed505d4 (do not edit this line) */
