/* Generated By:JJTree: Do not edit this line. ASTSubNode.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSubNode extends SimpleNode {
  public ASTSubNode(int id) {
    super(id);
  }

  public ASTSubNode(Calc p, int id) {
    super(p, id);
  }

/* inserted */
  public int calculate() {
    return jjtGetChild(0).calculate() - jjtGetChild(1).calculate();
  }
}
/* JavaCC - OriginalChecksum=7eb70ed04cb18119b1ff2a4ec8f38ca8 (do not edit this line) */
